{
 "title": "Minio dashboard",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "instance",
    "query": "label_values(minio_version_info,instance)"
   },
   { "name": "interval", "query": "2m,5m,10m,30m,1h" }
  ]
 },
 "panels": [
  {
   "type": "text",
   "description": "Minio is a high performance distributed object storage server, designed for large-scale private cloud infrastructure. For more information, check out the docs.",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 0 },
   "content": "<img src=\"https://min.io/resources/img/logo/MINIO_wordmark.png\" style=\"height: 40px;\"></img>\n<p style=\"margin-top: 20px;\"><small>\nMinio is a high performance distributed object storage server, designed for \nlarge-scale private cloud infrastructure. For more information, check out the <a href=\"https://docs.min.io\">docs</a>.\n</small></p>"
  },
  {
   "title": "Minio metadata size",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "minio_metadata_meta_data_size{instance=~\"$instance\"}",
     "legendFormat": "Metadata size in KB {{instance}}"
    }
   ]
  },
  {
   "title": "Minio healer running jobs",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "minio_healer_running_jobs{instance=~\"$instance\"}",
     "legendFormat": "Running healer jobs {{instance}}"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 3, "x": 0, "y": 6 },
   "format": "dtdurations",
   "valueName": "avg",
   "targets": [
    {
     "expr": "time() - max(process_start_time_seconds)",
     "legendFormat": "Start time of the Minio server"
    }
   ]
  },
  {
   "title": "Prometheus total http requests",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 3, "y": 6 },
   "targets": [
    {
     "expr": "sum(prometheus_http_requests_total)",
     "legendFormat": "Total http requests"
    }
   ]
  },
  {
   "title": "Minio total disks",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 4, "x": 8, "y": 6 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "expr": "avg(minio_disks_total)" }
   ]
  },
  {
   "title": "Minio metadata number of files",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "minio_metadata_number_of_files{instance=~\"$instance\"}",
     "legendFormat": "Number of files {{instance}}  in bucket {{bucket}}"
    }
   ]
  },
  {
   "title": "Memory and CPU",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "bytes", "label": "Memory" }
   ],
   "targets": [
    {
     "expr": "go_memstats_alloc_bytes{instance=~\"$instance\"}",
     "legendFormat": "Allocated {{instance}}"
    },
    {
     "expr": "rate(go_memstats_alloc_bytes_total{instance=~\"$instance\"}[2m])",
     "legendFormat": "Allocation rate {{instance}}"
    },
    {
     "expr": "rate(process_cpu_seconds_total{instance=~\"$instance\"}[2m])",
     "legendFormat": "CPU time {{instance}}"
    }
   ]
  },
  {
   "title": "Zerostor data size",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 13 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "minio_zerostor_data_size",
     "legendFormat": "Minio Zerostor data size {{instance}} namespace: {{namespace}}"
    }
   ]
  },
  {
   "title": "HTTP request rate per minute",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(code) (rate(promhttp_metric_handler_requests_total{instance=~\"$instance\"}[1m]))",
     "legendFormat": "status {{code}}"
    }
   ]
  },
  {
   "title": "S3 throughput",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 20 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "rate(s3_tx_bytes_total{instance=~\"$instance\"}[1m])",
     "legendFormat": "sent"
    },
    {
     "expr": "rate(s3_rx_bytes_total{instance=~\"$instance\"}[1m])",
     "legendFormat": "received"
    }
   ]
  },
  {
   "title": "Minio metadata free space",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "minio_metadata_meta_data_free_space",
     "legendFormat": "Metadata free space {{instance}}"
    }
   ]
  },
  {
   "title": "GO Memory Stats",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 27 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "go_memstats_alloc_bytes{instance=~\"$instance\"}",
     "legendFormat": "bytes allocated {{instance}}"
    },
    {
     "expr": "rate(go_memstats_alloc_bytes_total{instance=~\"$instance\"}[$interval])",
     "legendFormat": "alloc rate {{instance}}"
    },
    {
     "expr": "go_memstats_stack_inuse_bytes{instance=~\"$instance\"}",
     "legendFormat": "stack inuse {{instance}}"
    },
    {
     "expr": "go_memstats_heap_inuse_bytes{instance=~\"$instance\"}",
     "legendFormat": "heap inuse {{instance}}"
    }
   ]
  },
  {
   "title": "Minio available disk space",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 34 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "disk_storage_available",
     "legendFormat": "Disk storage available {{instance}}"
    }
   ]
  },
  {
   "title": "Backend storage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 34 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum by (address) (minio_zerostor_data_size{instance=~\"$instance\"})",
     "legendFormat": "shard {{address}}"
    }
   ]
  }
 ]
}