package tlog

import (
	"context"

	"github.com/minio/minio/cmd/gateway/zerostor/meta"
)

//Operation defines a tlog record type
type Operation string

const (
	// OperationSet set operation on store
	OperationSet = "set"
	//OperationDel del operation on store
	OperationDel = "del"
	//OperationLink link operation on store
	OperationLink = "link"

	//OperationTest is ignored always
	OperationTest = "test"

	//StateFile Tlog state, records the last state generated by this instance
	// used when the instance is running as a "master"
	StateFile = "tlog.state"

	//MasterStateFile keep track of the last received state from the master tlog
	// used when the instance is running as a "slave"
	MasterStateFile = "master.state"
)

/*
Recorder is a transaction log recoder. A recorder should be used as following

recorder.Begin()
defer recorder.End()
//DO YOUR WORK HERE

err := recorder.Record(rec)
*/
type Recorder interface {
	//Record creates a record and sets the state key if the creation was successful
	Record(record Record, setState bool) ([]byte, error)
	//Begin begins a record
	Begin()
	//End ends a record
	End()

	//SetState sets state at key
	SetState(key []byte) error
}

//TLogger interface
type TLogger interface {
	meta.Store
	Sync() error
	HealthChecker(ctx context.Context)
}

type fsTLogger struct {
	recorder *zdbRecorder
	meta.Store
}

//InitializeMetaManager creates a new zdb tlogger
func InitializeMetaManager(address, namespace, password, stateFile string, store meta.Store) (TLogger, error) {
	recorder, err := newZDBRecorder(address, namespace, password, stateFile)
	if err != nil {
		return nil, err
	}

	return &fsTLogger{
		recorder: recorder,
		Store:    store,
	}, nil
}
