name: Build Flist
on:
  push:
    branches:
      - '*'
    tags-ignore:
      - v*

jobs:
  build:
    name: Build and upload
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.1
      uses: actions/setup-go@v1
      with:
        go-version: 1.14
      id: go

    - name: Checkout code into the Go module directory
      uses: actions/checkout@v1

    - name: Build binaries
      run: |
        make getdeps
        make
        make entrypoint
      env:
        GO111MODULE: on

    - name: Collecting files
      run: |
        scripts/collect.sh ${{ github.workspace }}/archive
    - name: Set name of the development build
      id: setname
      run: |
        echo "::set-output name=build::minio:v$(date +%y%m%d.%-H%M%S.0)-dev.flist"

    - name: Publish flist (${{ github.sha }})
      if: success()
      uses: threefoldtech/publish-flist@master
      with:
        token: ${{ secrets.HUB_JWT }}
        action: publish
        user: tf-autobuilder
        root: archive
        name: minio-${{ github.sha }}-bins.flist

    - name: merge with base
      if: success()
      uses: threefoldtech/publish-flist@master
      with:
        token: ${{ secrets.HUB_JWT }}
        action: merge
        user: tf-autobuilder
        name: ${{ steps.setname.outputs.build }}
        target: tf-official-apps/base:latest.flist tf-autobuilder/minio-${{ github.sha }}-bins.flist

    - name: Crosslink flist (development)
      if: success() && github.ref == 'refs/heads/master-rework'
      uses: threefoldtech/publish-flist@master
      with:
        token: ${{ secrets.HUB_JWT }}
        action: crosslink
        user: tf-official-apps
        name: minio:latest.flist
        target: tf-autobuilder/${{ steps.setname.outputs.build }}
